plugin: amazon.aws.aws_ec2
regions:
  - "us-east-1"
filters:
  #stag:Cluster: "{{ cluster_name }}"
  tag:Cluster: "k8s-cluster-from-ground-up"
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: role
groups:
  masters: "'control-plane' in tags.Role"
  workers: "'worker' in tags.Role"
hostvars:
  ansible_user: ubuntu # already in config file, did not work anyways
  ansible_ssh_private_key_file: "./k8s-cluster-from-ground-up-key.pem" # already in config file
